#' Scale Environmental Rasters Using Species Occurrence Data
#'
#' Preprocessing function that standardizes raster files using precomputed mean
#' and standard deviation values from species occurrence data. Supports both
#' static and dynamic (time-varying) rasters.
#'
#' @param input_dir Character. Directory containing input .tif raster files.
#' @param output_dir Character. Directory where scaled rasters will be saved.
#' @param scaling_params_file Character. Path to CSV file with columns:
#'   variable, mean, sd. Typically generated by
#'   \code{\link{temporally_explicit_extraction}}.
#' @param variable_patterns Named character vector mapping variable names to
#'   raster filename patterns. Time placeholders (e.g., YEAR, MONTH) must match
#'   time_cols. Static variables have no placeholders.
#' @param time_cols Character vector of time placeholders for dynamic variables.
#'   Default is NULL.
#' @param output_suffix Character. Suffix to append to output raster filenames.
#'   Default is "_Scaled".
#' @param overwrite Logical. If TRUE, existing output files will be overwritten.
#'   If FALSE, existing files are skipped. Default is FALSE.
#'
#' @details
#' Dynamic variables are detected when patterns contain placeholders
#' corresponding to time_cols. Static variables are scaled once. Scaling applies
#' z-score transformation: (value - mean) / sd. Scaled rasters are written to
#' output_dir.
#'
#' Scaled rasters should use the same scaling parameters derived from species
#' occurrence data to ensure consistent standardization between training data
#' and prediction layers.
#'
#' @seealso
#' Preprocessing: \code{\link{temporally_explicit_extraction}},
#' \code{\link{raster_align}}
#'
#' @examples
#' \dontrun{
#' variable_patterns <- c(
#'   "bio1" = "bio1_YEAR",
#'   "temp" = "temp_YEAR_MONTH",
#'   "elevation" = "elevation"
#' )
#'
#' scale_rasters(
#'   input_dir = "aligned_rasters/",
#'   output_dir = "scaled_rasters/",
#'   scaling_params_file = "extracted_values/Scaling_Parameters.csv",
#'   variable_patterns = variable_patterns,
#'   time_cols = c("YEAR", "MONTH")
#' )
#' }
#'
#' @export
#' @importFrom terra rast writeRaster
#' @importFrom utils read.csv
scale_rasters <- function(input_dir,
                          output_dir,
                          scaling_params_file,
                          variable_patterns,
                          time_cols = NULL,
                          output_suffix = "_Scaled",
                          overwrite = F) {

  require(terra)
  require(readr)

  ### Validate variable_patterns format
  if (!is.vector(variable_patterns) || is.null(names(variable_patterns))) {
    stop(paste(
      "ERROR: variable_patterns must be a named vector.",
      "",
      "### Example format:",
      "#",
      "# variable_patterns <- c(",
      "#   \"VariableName1\" = \"VariableName1_YEAR\",",
      "#   \"VariableName2\" = \"VariableName2_MONTH_YEAR\",",
      "#   \"StaticVariable\" = \"StaticVariable\"",
      "# )",
      "#",
      "# - NAME (left): output column name",
      "# - VALUE (right): pattern to match in raster filenames",
      "# - Time-varying: use placeholders (YEAR, MONTH, etc.) matching time_cols",
      "# - Static: use simple pattern with no time placeholders",
      sep = "\n"
    ))
  }

  if (any(names(variable_patterns) == "")) {
    stop("ERROR: All elements in variable_patterns must be named")
  }

  ### Validate input directory
  if (!dir.exists(input_dir)) {
    stop(paste0("ERROR: Input directory does not exist: ", input_dir))
  }

  ### Validate scaling parameters file
  if (!file.exists(scaling_params_file)) {
    stop(paste0("ERROR: Scaling parameters file does not exist: ", scaling_params_file))
  }

  ### Create output directory
  dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

  ### Load scaling parameters
  scaling_params <- read_csv(scaling_params_file, show_col_types = FALSE)
  print(paste("Loaded scaling parameters for", nrow(scaling_params), "variables"))

  ### Check if all variables in variable_patterns have scaling parameters
  missing_params <- setdiff(names(variable_patterns), scaling_params$variable)
  if (length(missing_params) > 0) {
    warning(paste0("WARNING: The following variables lack scaling parameters: ",
                   paste(missing_params, collapse = ", ")))
  }

  ### Get all files
  all_files <- list.files(path = input_dir, pattern = "tif",
                          recursive = TRUE, full.names = TRUE)
  print(paste("Found", length(all_files), "raster files"))

  if (length(all_files) == 0) {
    stop(paste0("ERROR: No .tif files found in input directory: ", input_dir))
  }

  ### Print overwrite mode
  if (overwrite) {
    print("Overwrite mode: ON - Will process and overwrite all files")
  } else {
    print("Overwrite mode: OFF - Will skip files that already exist")
  }

  ### Determine which variables are static vs dynamic
  static_vars <- c()
  dynamic_vars <- c()
  for (var_name in names(variable_patterns)) {
    pattern <- variable_patterns[var_name]
    has_time_component <- any(sapply(time_cols, function(tc) {
      grepl(tc, pattern, ignore.case = TRUE)
    }))
    if (has_time_component) {
      dynamic_vars <- c(dynamic_vars, var_name)
    } else {
      static_vars <- c(static_vars, var_name)
    }
  }

  print(paste("Dynamic variables:", ifelse(length(dynamic_vars) > 0,
                                           paste(dynamic_vars, collapse = ", "),
                                           "none")))
  print(paste("Static variables:", ifelse(length(static_vars) > 0,
                                          paste(static_vars, collapse = ", "),
                                          "none")))

  ### Validate time_cols match variable_patterns
  if (length(dynamic_vars) > 0) {
    if (is.null(time_cols) || length(time_cols) == 0) {
      stop(paste(
        "ERROR: time_cols is required when variable_patterns contain time placeholders.",
        "",
        "### Examples:",
        "# time_cols = \"Year\"",
        "# time_cols = c(\"Year\", \"Month\")",
        sep = "\n"
      ))
    }

    pattern_time_placeholders <- c()
    for (var_name in dynamic_vars) {
      pattern <- variable_patterns[var_name]
      pattern_parts <- strsplit(pattern, "_")[[1]]
      for (part in pattern_parts) {
        if (toupper(part) %in% toupper(time_cols)) {
          pattern_time_placeholders <- c(pattern_time_placeholders, toupper(part))
        }
      }
    }

    pattern_time_placeholders <- unique(pattern_time_placeholders)
    time_cols_upper <- toupper(time_cols)
    missing_in_patterns <- time_cols_upper[!time_cols_upper %in% pattern_time_placeholders]
    extra_in_patterns <- pattern_time_placeholders[!pattern_time_placeholders %in% time_cols_upper]

    if (length(missing_in_patterns) > 0 && length(pattern_time_placeholders) > 0) {
      warning(paste(
        "WARNING: time_cols includes columns not found as placeholders in variable_patterns:",
        paste(missing_in_patterns, collapse = ", "),
        "This may indicate a mismatch between your time_cols and variable_patterns.",
        "",
        "Your time_cols:", paste(time_cols, collapse = ", "),
        "Placeholders in patterns:", paste(pattern_time_placeholders, collapse = ", ")
      ))
    }

    if (length(extra_in_patterns) > 0) {
      stop(paste(
        "ERROR: variable_patterns contain time placeholders not in time_cols:",
        paste(extra_in_patterns, collapse = ", "),
        "",
        "Your time_cols:", paste(time_cols, collapse = ", "),
        "Placeholders in patterns:", paste(pattern_time_placeholders, collapse = ", "),
        "",
        "### Fix by adding missing columns to time_cols:",
        "# time_cols = c(\"", paste(c(time_cols, tolower(extra_in_patterns)), collapse = "\", \""), "\")",
        sep = "\n"
      ))
    }
  }

  if (length(dynamic_vars) > 0 && (is.null(time_cols) || length(time_cols) == 0)) {
    stop(paste(
      "ERROR: Dynamic variables detected in variable_patterns, but time_cols is NULL or empty.",
      "",
      "### Provide time_cols:",
      "# time_cols = \"Year\"",
      "# time_cols = c(\"Year\", \"Month\")",
      sep = "\n"
    ))
  }

  ### Scale static variables
  static_vars_scaled <- 0
  if (length(static_vars) > 0) {
    print("Processing static variables...")
    for (var_name in static_vars) {
      print(paste("Processing static variable:", var_name))
      var_params <- scaling_params[scaling_params$variable == var_name, ]
      if (nrow(var_params) == 0) {
        print(paste0("  Skipping ", var_name, " - no scaling parameters found"))
        next
      }
      var_mean <- var_params$mean
      var_sd <- var_params$sd
      search_pattern <- variable_patterns[var_name]
      candidate_files <- all_files[sapply(all_files, function(f) {
        filename <- basename(f)
        grepl(paste0("^", var_name), filename, ignore.case = TRUE)
      })]
      if (length(candidate_files) == 0) {
        print(paste0("  Warning: No files found for ", var_name))
        next
      }
      output_file <- file.path(output_dir, paste0(var_name, output_suffix, ".tif"))
      if (file.exists(output_file) && !overwrite) {
        print("  Skipped (already exists)")
        static_vars_scaled <- static_vars_scaled + 1
      } else {
        file <- candidate_files[1]
        raster_layer <- terra::rast(file)
        raster_scaled <- (raster_layer - var_mean) / var_sd
        terra::writeRaster(raster_scaled, output_file, overwrite = overwrite)
        print("  Processed and saved")
        static_vars_scaled <- static_vars_scaled + 1
      }
    }
  }

  ### Scale dynamic variables
  ### Scale dynamic variables
  dynamic_vars_scaled <- 0
  if (length(dynamic_vars) > 0) {
    print("Processing dynamic variables...")
    for (var_name in dynamic_vars) {

      ### Message at start of each dynamic variable
      print(paste("Scaling dynamic variable:", var_name))

      var_params <- scaling_params[scaling_params$variable == var_name, ]
      if (nrow(var_params) == 0) {
        print(paste0("  Skipping ", var_name, " - no scaling parameters found"))
        next
      }
      var_mean <- var_params$mean
      var_sd <- var_params$sd
      search_pattern <- variable_patterns[var_name]

      # Determine which time columns are actually in this variable's pattern
      relevant_time_cols <- time_cols[sapply(time_cols, function(tc) {
        grepl(tc, search_pattern, ignore.case = TRUE)
      })]

      candidate_files <- all_files[sapply(all_files, function(f) {
        filename <- basename(f)
        grepl(paste0("^", var_name), filename, ignore.case = TRUE)
      })]
      if (length(candidate_files) == 0) {
        print(paste0("  Warning: No files found for ", var_name))
        next
      }
      print(paste("  Found", length(candidate_files), "candidate files"))

      time_file_pairs <- list()
      for (file in candidate_files) {
        filename <- basename(file)
        time_vals <- list()
        all_found <- TRUE
        filename_no_ext <- gsub("\\.(tif|TIF)$", "", filename)
        filename_parts <- strsplit(filename_no_ext, "_")[[1]]
        pattern_parts <- strsplit(search_pattern, "_")[[1]]

        # Only extract time columns that are in this variable's pattern
        for (tc in relevant_time_cols) {
          tc_positions <- which(toupper(pattern_parts) == toupper(tc))
          if (length(tc_positions) > 0) {
            tc_pos <- tc_positions[1]
            if (tc_pos <= length(filename_parts)) {
              value <- filename_parts[tc_pos]
              if (grepl("^\\d+$", value)) {
                time_vals[[tc]] <- value
              } else {
                num_match <- regmatches(value, gregexpr("\\d+", value))[[1]]
                if (length(num_match) > 0) {
                  time_vals[[tc]] <- num_match[1]
                } else {
                  all_found <- FALSE
                  break
                }
              }
            } else {
              all_found <- FALSE
              break
            }
          } else {
            all_found <- FALSE
            break
          }
        }

        if (all_found && length(time_vals) == length(relevant_time_cols)) {
          test_pattern <- search_pattern
          for (tc in relevant_time_cols) {
            test_pattern <- gsub(tc, time_vals[[tc]], test_pattern, ignore.case = TRUE)
          }
          test_parts <- strsplit(test_pattern, "_")[[1]]
          match_count <- sum(sapply(test_parts, function(part) {
            grepl(part, filename, ignore.case = TRUE)
          }))
          if (match_count >= length(test_parts) * 0.8) {
            ### Check for duplicates in SOURCE files (not output files)
            time_string <- paste(sapply(relevant_time_cols, function(tc) time_vals[[tc]]), collapse = "_")

            # Check if we already have a source file for this time step
            existing_match <- FALSE
            for (existing_file in names(time_file_pairs)) {
              existing_vals <- time_file_pairs[[existing_file]]
              if (identical(existing_vals, time_vals)) {
                existing_match <- TRUE
                break
              }
            }

            if (existing_match) {
              stop(paste0("ERROR: Multiple rasters found for variable '", var_name,
                          "' at the same time step (", time_string, ")."))
            }

            time_file_pairs[[file]] <- time_vals
          }
        }
      }

      if (length(time_file_pairs) == 0) {
        print(paste0("  Warning: No valid time information found in filenames for ", var_name))
        next
      }

      print(paste("  Processing", length(time_file_pairs), "time periods"))
      processed_count <- 0
      skipped_count <- 0

      for (file in names(time_file_pairs)) {
        time_vals <- time_file_pairs[[file]]
        time_string <- paste(sapply(relevant_time_cols, function(tc) time_vals[[tc]]), collapse = "_")
        output_file <- file.path(output_dir, paste0(var_name, "_", time_string, output_suffix, ".tif"))
        if (file.exists(output_file) && !overwrite) {
          skipped_count <- skipped_count + 1
          next
        }
        raster_layer <- terra::rast(file)
        raster_scaled <- (raster_layer - var_mean) / var_sd
        terra::writeRaster(raster_scaled, output_file, overwrite = overwrite)
        processed_count <- processed_count + 1
      }

      if (processed_count > 0 || skipped_count > 0) {
        dynamic_vars_scaled <- dynamic_vars_scaled + 1
      }

      print(paste("  Processed:", processed_count, "| Skipped:", skipped_count))
    }
  }

  ### Check if no variables were scaled
  total_vars_scaled <- static_vars_scaled + dynamic_vars_scaled
  if (total_vars_scaled == 0) {
    stop(paste(
      "ERROR: No raster files could be matched and scaled for any variables.",
      "",
      "### Example variable_patterns:",
      "# variable_patterns <- c(",
      "#   \"VariableName1\" = \"VariableName1_YEAR\",",
      "#   \"VariableName2\" = \"VariableName2_MONTH_YEAR\",",
      "#   \"StaticVariable\" = \"StaticVariable\"",
      "# )",
      "#",
      "# Ensure patterns match your actual raster filenames",
      sep = "\n"
    ))
  }

  if (static_vars_scaled > 0 && dynamic_vars_scaled == 0 && length(dynamic_vars) > 0 && !overwrite) {
    warning(paste(
      "WARNING: Only static variables matched and scaled. No raster files found for dynamic variables.",
      "",
      "Check that:",
      "1. Raster filenames contain time values (e.g., 2020, 2021)",
      "2. variable_patterns use correct placeholders matching time_cols",
      "3. Time values in filenames match your scaling parameters",
      "",
      "Note: Set overwrite = TRUE to reprocess existing files"
    ))
  } else if (static_vars_scaled > 0 && dynamic_vars_scaled == 0 && length(dynamic_vars) > 0 && overwrite) {
    warning(paste(
      "WARNING: Only static variables matched and scaled. No raster files found for dynamic variables.",
      "",
      "Check that:",
      "1. Raster filenames contain time values (e.g., 2020, 2021)",
      "2. variable_patterns use correct placeholders matching time_cols",
      "3. Time values in filenames match your scaling parameters"
    ))
  }

  print("All scaling complete!")
  print(paste("Successfully scaled", total_vars_scaled, "variables"))
  print(paste("  Static:", static_vars_scaled, "| Dynamic:", dynamic_vars_scaled))

  return(invisible(NULL))
}
